import { Response } from 'express';
import { AuthenticatedRequest } from '../../interfaces/AuthenticatedRequest';
import { makeSendMessageUseCase } from '../../factories/messaging/makeMessagingUseCases';
import { MessagingChannel } from '../../../domain/messaging/MessagingChannel';

/**
 * @swagger
 * /api/messaging/message/send:
 *   post:
 *     tags:
 *       - Messaging (Multi-Channel)
 *     summary: Send a message
 *     description: Send a message through any supported messaging channel (agnostic of channel)
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               channel:
 *                 $ref: '#/components/schemas/MessagingChannel'
 *               channelInstanceId:
 *                 type: string
 *                 example: 'my-whatsapp-instance'
 *                 description: Instance ID (previously created via POST /api/messaging/instance)
 *               remoteJid:
 *                 type: string
 *                 example: '5585999999999'
 *                 description: Recipient (phone for WhatsApp, ID for Telegram, email for Email, etc.)
 *               message:
 *                 type: string
 *                 example: 'Hello! This is a test message.'
 *               mediaUrl:
 *                 type: string
 *                 example: 'https://example.com/image.jpg'
 *                 description: Optional URL to media file
 *               mediaType:
 *                 type: string
 *                 enum: ['image', 'audio', 'document', 'video']
 *                 example: 'image'
 *                 description: Type of media if mediaUrl is provided
 *             required:
 *               - channel
 *               - channelInstanceId
 *               - remoteJid
 *               - message
 *     responses:
 *       200:
 *         description: Message sent successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: 'Mensagem enviada com sucesso'
 *                 data:
 *                   type: object
 *                   properties:
 *                     messageId:
 *                       type: string
 *                       example: 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
 *                       description: Internal message ID
 *                     channelMessageId:
 *                       type: string
 *                       example: 'whatsapp-msg-12345'
 *                       description: Message ID generated by the channel provider
 *                     status:
 *                       type: string
 *                       example: 'sent'
 *                     timestamp:
 *                       type: string
 *                       format: date-time
 *                       example: '2024-01-15T10:30:00Z'
 *       400:
 *         description: Bad request - missing required fields, invalid channel, or instance not found
 *       401:
 *         description: Unauthorized - invalid or missing authentication token
 *       500:
 *         description: Internal server error
 */
export class SendMessageController {
  async handle(req: AuthenticatedRequest, res: Response): Promise<Response> {
    try {
      const { channel, channelInstanceId, remoteJid, message, mediaUrl, mediaType } = req.body;
      const userId = req.user?.id;

      if (!userId) {
        return res.status(401).json({ error: 'Usuário não autenticado' });
      }

      if (!channel || !channelInstanceId || !remoteJid || !message) {
        return res.status(400).json({ 
          error: 'Campos obrigatórios: channel, channelInstanceId, remoteJid, message' 
        });
      }

      const useCase = makeSendMessageUseCase();
      const result = await useCase.execute({
        userId,
        channel: channel as MessagingChannel,
        channelInstanceId,
        remoteJid,
        message,
        mediaUrl,
        mediaType,
      });

      return res.status(200).json({
        success: true,
        message: 'Mensagem enviada com sucesso',
        data: result,
      });
    } catch (error: any) {
      return res.status(400).json({
        success: false,
        error: error.message,
      });
    }
  }
}

export function makeSendMessageController(): SendMessageController {
  return new SendMessageController();
}
